[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm ci && npm run build"

[deploy]
startCommand = "cd backend && npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment variables that Railway should use
[env]
NODE_ENV = "production"
PORT = "3001"

# Tell Railway to use the backend directory as root
workdir = "backend"

[variables]
NIXPACKS_NODE_VERSION = "18" 