import React from 'react'
import { useWizardSteps, useWizardData } from '../Shared/hooks'
import { SocialMediaState } from '../Shared/types'
import { WizardLayout } from '../Shared/WizardLayout'
import { PlatformSelector } from '../../components/PlatformSelector'
import { ObjectiveSelector } from '../../components/ObjectiveSelector'
import { StyleSelector } from '../../components/StyleSelector'
import { ContentInputs } from '../../components/ContentInputs'
import { TrendingHooks } from '../../components/TrendingHooks'
import { AnimePersonaSelector } from '../../components/AnimePersonaSelector'
import { PostPreview } from '../../components/PostPreview'

interface SocialMediaWizardProps {
  onBack: () => void
}

const initialState: SocialMediaState = {
  step: 1,
  contentType: 'social-media',
  platform: 'linkedin',
  audience: 'industry_peers',
  objective: 'Introduce product',
  tone: 'Professional',
  stylePack: 'professional',
  animePersona: '',
  topic: '',
  keyPoints: [],
  pastPost: '',
  customInstructions: '',
  trendingHashtags: [],
  showTemplates: false,
  isGenerating: false,
  generatedPost: '',
  characterCount: 0,
  maxLength: 3000,
  withinLimit: true,
  uploadedImages: [],
  showImageUpload: false,
  showSpeechToText: false,
  speechTranscript: '',
  showAnimePersona: false,
  generateVariations: false,
  variations: [],
  selectedVariation: null
}

const stepTitles = [
  'Platform & Audience',
  'Objective',
  'Style & Tone',
  'Content Input',
  'Trending Hooks',
  'Enhancement & Persona',
  'Preview & Generate'
]

const SocialMediaWizard: React.FC<SocialMediaWizardProps> = ({ onBack }) => {
  const { data: state, update: updateState } = useWizardData(initialState)
  
  const validateStep = (step: number): boolean => {
    switch (step) {
      case 1: return state.platform && state.audience ? true : false
      case 2: return state.objective ? true : false
      case 3: return state.tone ? true : false
      case 4: return state.topic.trim().length > 0
      case 5: return true // Optional step
      case 6: return true // Optional step
      case 7: return true
      default: return false
    }
  }

  const { currentStep, next, prev, canProceed } = useWizardSteps(7, validateStep)

  const generatePost = async () => {
    updateState('isGenerating', true)
    // TODO: Implement actual generation logic
    setTimeout(() => {
      updateState('generatedPost', `Generated social media post for ${state.platform}:\n\n${state.topic}\n\nThis is a placeholder post that would be generated by the AI.`)
      updateState('isGenerating', false)
    }, 2000)
  }

  const renderStepContent = () => {
    switch (currentStep) {
      case 1:
        return (
          <div className="space-y-6">
            <h3 className="text-xl font-semibold mb-4">Select Platform & Audience</h3>
            <PlatformSelector
              selectedPlatform={state.platform}
              selectedAudience={state.audience}
              onPlatformChange={(platform) => updateState('platform', platform)}
              onAudienceChange={(audience) => updateState('audience', audience)}
            />
          </div>
        )
      case 2:
        return (
          <div className="space-y-6">
            <h3 className="text-xl font-semibold mb-4">What's Your Objective?</h3>
            <ObjectiveSelector
              selectedObjective={state.objective}
              onObjectiveChange={(objective) => updateState('objective', objective)}
              platform={state.platform}
            />
          </div>
        )
      case 3:
        return (
          <div className="space-y-6">
            <h3 className="text-xl font-semibold mb-4">Choose Style & Tone</h3>
            <StyleSelector
              selectedTone={state.tone}
              selectedStylePack={state.stylePack}
              onToneChange={(tone) => updateState('tone', tone)}
              onStylePackChange={(stylePack) => updateState('stylePack', stylePack)}
              platform={state.platform}
            />
          </div>
        )
      case 4:
        return (
          <div className="space-y-6">
            <h3 className="text-xl font-semibold mb-4">Tell Us About Your Content</h3>
            <ContentInputs
              topic={state.topic}
              keyPoints={state.keyPoints}
              pastPost={state.pastPost}
              customInstructions={state.customInstructions}
              onTopicChange={(topic) => updateState('topic', topic)}
              onKeyPointsChange={(keyPoints) => updateState('keyPoints', keyPoints)}
              onPastPostChange={(pastPost) => updateState('pastPost', pastPost)}
              onCustomInstructionsChange={(customInstructions) => updateState('customInstructions', customInstructions)}
            />
          </div>
        )
      case 5:
        return (
          <div className="space-y-6">
            <h3 className="text-xl font-semibold mb-4">Trending Hooks & Hashtags</h3>
            <TrendingHooks
              platform={state.platform}
              trendingHashtags={state.trendingHashtags}
              onTrendingHashtagsChange={(hashtags) => updateState('trendingHashtags', hashtags)}
            />
          </div>
        )
      case 6:
        return (
          <div className="space-y-6">
            <h3 className="text-xl font-semibold mb-4">Enhancement & Persona</h3>
            <div className="bg-purple-50 rounded-lg p-6 border border-purple-200">
              <div className="flex items-center justify-between mb-4">
                <h4 className="font-semibold text-purple-800">🎭 Anime Persona (Optional)</h4>
                <button
                  onClick={() => updateState('showAnimePersona', !state.showAnimePersona)}
                  className={`px-4 py-2 rounded-lg text-sm transition-all duration-300 ${
                    state.showAnimePersona
                      ? 'bg-purple-500 text-white'
                      : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                  }`}
                >
                  {state.showAnimePersona ? 'Hide Personas' : 'Choose Persona'}
                </button>
              </div>
              
              {state.showAnimePersona && (
                <AnimePersonaSelector
                  selectedPersona={state.animePersona}
                  onPersonaChange={(persona) => updateState('animePersona', persona)}
                  platform={state.platform}
                />
              )}
            </div>
          </div>
        )
      case 7:
        return (
          <div className="space-y-6">
            <h3 className="text-xl font-semibold mb-4">Preview & Generate</h3>
            
            {/* Settings Summary */}
            <div className="bg-gray-50 rounded-lg p-6 border border-gray-200">
              <h4 className="font-semibold mb-4">📋 Your Settings</h4>
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div><strong>Platform:</strong> {state.platform}</div>
                <div><strong>Audience:</strong> {state.audience}</div>
                <div><strong>Objective:</strong> {state.objective}</div>
                <div><strong>Style:</strong> {state.tone} ({state.stylePack})</div>
                {state.animePersona && (
                  <div className="col-span-2"><strong>Persona:</strong> {state.animePersona}</div>
                )}
                <div className="col-span-2"><strong>Topic:</strong> {state.topic}</div>
              </div>
            </div>

            {/* Generate Button */}
            <button
              onClick={generatePost}
              disabled={state.isGenerating || !state.topic.trim()}
              className="w-full px-6 py-4 bg-gradient-to-r from-purple-500 to-pink-500 text-white rounded-xl hover:from-purple-600 hover:to-pink-600 disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-300 shadow-lg hover:shadow-xl transform hover:scale-105 flex items-center justify-center gap-3 text-lg font-medium"
            >
              {state.isGenerating ? (
                <>
                  <div className="animate-spin w-5 h-5 border-2 border-white border-t-transparent rounded-full"></div>
                  Generating Post...
                </>
              ) : (
                <>
                  <span className="text-xl">✨</span>
                  Generate Social Media Post
                </>
              )}
            </button>

            {/* Generated Content */}
            {state.generatedPost && (
              <PostPreview
                content={state.generatedPost}
                platform={state.platform}
                characterCount={state.characterCount}
                maxLength={state.maxLength}
                withinLimit={state.withinLimit}
              />
            )}
          </div>
        )
      default:
        return null
    }
  }

  return (
    <WizardLayout
      currentStep={currentStep}
      totalSteps={7}
      stepTitle={stepTitles[currentStep - 1]}
      onNext={currentStep === 7 ? generatePost : next}
      onPrev={prev}
      onBack={onBack}
      canProceed={canProceed}
    >
      {renderStepContent()}
    </WizardLayout>
  )
}

export default SocialMediaWizard 