# .github/workflows/deploy-frontend.yml
name: Deploy React App to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      contents: write   # to write to the gh-pages branch
      deployments: write # to create deployments
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        working-directory: ./frontend
        run: |
          npm ci
          echo "✅ Dependencies installed"
      
      - name: Create production environment file
        working-directory: ./frontend
        run: |
          echo "Creating .env.production file..."
          echo "VITE_API_URL=https://yumi-series-production.up.railway.app" > .env.production
          echo "VITE_FRONTEND_URL=http://yumi77965.online" >> .env.production
          echo "=== .env.production created ==="
          cat .env.production
          echo "=========================="
      
      - name: Build with Vite
        working-directory: ./frontend
        run: |
          echo "🏗️ Starting build..."
          npm run build
          echo "✅ Build completed"
        env:
          NODE_ENV: production
          VITE_API_URL: https://yumi-series-production.up.railway.app
          VITE_FRONTEND_URL: http://yumi77965.online
      
      - name: Verify build created dist directory
        run: |
          echo "=== Checking if build succeeded ==="
          if [ ! -d "frontend/dist" ]; then
            echo "❌ ERROR: frontend/dist directory not found!"
            echo "Build failed - dist directory was not created"
            exit 1
          fi
          
          echo "✅ frontend/dist directory exists"
          echo "=== Directory contents ==="
          ls -la frontend/dist/
          
          echo "=== Checking critical files ==="
          if [ ! -f "frontend/dist/index.html" ]; then
            echo "❌ ERROR: index.html not found in dist!"
            exit 1
          fi
          
          if [ ! -d "frontend/dist/assets" ]; then
            echo "❌ ERROR: assets directory not found in dist!"
            exit 1
          fi
          
          echo "✅ All critical files found"
          echo "=== File sizes ==="
          du -sh frontend/dist/*
          
          echo "=== Upload path confirmation ==="
          echo "Will upload: $(pwd)/frontend/dist"
          echo "Upload path exists: $(test -d frontend/dist && echo 'YES' || echo 'NO')"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          cname: yumi77965.online
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'deploy: Update GitHub Pages'
